const SETTINGS = {
   DEFAULT_SPEED: 1,
   DEFAULT_SPEED_MIN: 1,
   DEFAULT_SPEED_MAX: 100,
   DEFAULT_SPEED_STEP: 10,
   DEFAULT_CHARACTER_NAME: "Неизвестный",
   DEFAULT_CHARACTER_INVENTORY_MAX: 20
};